# Generated by Django 5.0 on 2025-12-03 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role', models.CharField(max_length=50)),
                ('role_display', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('paid', 'Paid')], default='generated', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payment_slips', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Slip',
                'verbose_name_plural': 'Payment Slips',
                'db_table': 'payment_slips',
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
