# Generated by Django 5.0 on 2025-12-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='password_changed',
            field=models.BooleanField(default=False, help_text='Whether the user has changed their password (for clients/agents)'),
        ),
    ]
