# Generated by Django 5.0 on 2025-12-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_paymentslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='pay_slip_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
