# Generated by Django 5.0 on 2025-12-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_clientformsubmission_employeeformsubmission'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientformsubmission',
            table='client_form_submissions',
        ),
        migrations.AlterModelTable(
            name='employeeformsubmission',
            table='employee_form_submissions',
        ),
    ]
