# Generated by Django 5.0 on 2025-12-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('published', 'Published'), ('paid', 'Paid')], default='generated', max_length=20),
        ),
    ]
