# Generated by Django 5.0 on 2025-12-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_paymentslip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('paid', 'Paid')], default='generated', max_length=20),
        ),
    ]
