# Generated by Django 5.0 on 2025-12-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_paymentslip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='overtime_hours_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
