# Generated by Django 5.0 on 2025-12-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_paymentslip_overtime_hours_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='payment_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
