# Generated by Django 5.0 on 2025-12-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_paymentslip_payment_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentslip',
            name='payment_uploaded',
        ),
    ]
