# Generated by Django 5.0 on 2025-12-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_paymentslip_payment_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
