# Generated by Django 5.0 on 2025-12-18 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_add_payment_slip_upload_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Reason for removal request', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on approval/rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(help_text='HR staff who requested the removal', on_delete=django.db.models.deletion.CASCADE, related_name='removal_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removal_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Removal Request',
                'verbose_name_plural': 'Employee Removal Requests',
                'db_table': 'employee_removal_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
