# Generated by Django 5.0 on 2026-02-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userrole_password_changed'),
        ('authentication', '0014_employeeremovalrequest'),
    ]

    operations = [
    ]
