# Generated by Django 5.0 on 2026-02-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_merge_20260210_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientformsubmission',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientformsubmission',
            name='agent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientformsubmission',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
