# Generated by Django 5.0 on 2026-02-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_add_coordinator_and_assigned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='custom_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom salary override; if set, takes precedence over the role default', max_digits=10, null=True),
        ),
    ]
