# Generated by Django 5.0 on 2026-02-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_add_custom_salary_to_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='password_changed',
            field=models.BooleanField(default=True, help_text='Whether the user has changed their password (False only for auto-created accounts)'),
        ),
    ]
