# Generated by Django 5.0 on 2026-02-19 07:55

from django.db import migrations


def set_existing_password_changed_true(apps, schema_editor):
    """Set password_changed=True for all existing users so they aren't forced to change."""
    UserRole = apps.get_model('authentication', 'UserRole')
    UserRole.objects.filter(password_changed=False).update(password_changed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_change_password_changed_default_true'),
    ]

    operations = [
        migrations.RunPython(
            set_existing_password_changed_true,
            migrations.RunPython.noop,
        ),
    ]
