# Generated by Django 5.0 on 2026-02-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_set_existing_users_password_changed_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientformsubmission',
            name='coordinator_response',
            field=models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Coordinator response to the assignment', max_length=20),
        ),
        migrations.AddField(
            model_name='clientformsubmission',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting the assignment (if rejected)', null=True),
        ),
        migrations.AddField(
            model_name='clientformsubmission',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When the coordinator responded to the assignment', null=True),
        ),
    ]
