# Generated by Django 5.0 on 2026-02-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_add_password_reset_otp'),
        ('authentication', '0022_coordinator_assignment_model'),
    ]

    operations = [
    ]
