# Generated by Django 5.0 on 2026-02-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_merge_20260217_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientformsubmission',
            name='project_created',
            field=models.BooleanField(default=False, help_text='Whether a project has been created from this submission'),
        ),
    ]
