# Generated by Django 5.0 on 2026-02-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_rename_hr_staff_to_hr_head'),
        ('authentication', '0024_add_project_created_field'),
    ]

    operations = [
    ]
