# Generated by Django 5.0 on 2026-01-24 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_merge_20260218_1417'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeremovalrequest',
            name='requested_by',
            field=models.ForeignKey(help_text='HR Head who requested the removal', on_delete=django.db.models.deletion.CASCADE, related_name='removal_requests_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
