# Generated by Django 5.0 on 2025-11-28 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
