# Generated by Django 5.0 on 2025-11-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_assigned_agent_project_assigned_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_agent',
            field=models.BooleanField(default=False, help_text='Whether this project requires an agent'),
        ),
    ]
