# Generated by Django 5.0 on 2025-12-02 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_accessor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role': 'accessor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessor_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_senior_valuer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role': 'senior_valuer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_valuer_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
