# Generated by Django 5.0 on 2025-12-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_assigned_accessor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agent_info',
            field=models.JSONField(blank=True, help_text='Agent information from project creation form', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_info',
            field=models.JSONField(blank=True, help_text='Client information from project creation form', null=True),
        ),
    ]
