# Generated by Django 5.0 on 2025-12-02 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_agent_info_project_client_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The assigned user this document is intended for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
