# Generated by Django 5.0 on 2025-12-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_workflow_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='md_gm_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='MD/GM approval status for the project', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='md_gm_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='md_gm_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='md_gm_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection by MD/GM (if rejected)', null=True),
        ),
    ]
