# Generated by Django 5.0 on 2026-02-16 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text='Estimated value/cost for the project', max_digits=12),
        ),
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_value', models.DecimalField(decimal_places=2, help_text='Estimated value for this project payment', max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Payment Requested'), ('submitted', 'Bank Slip Submitted'), ('under_review', 'Under Review'), ('approved', 'Payment Approved'), ('rejected', 'Payment Rejected')], default='pending', max_length=20)),
                ('bank_slip', models.FileField(blank=True, help_text='Bank slip uploaded by client', null=True, upload_to='project_payments/bank_slips/%Y/%m/')),
                ('bank_slip_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('payment_requested_at', models.DateTimeField(blank=True, null=True)),
                ('payment_approved_at', models.DateTimeField(blank=True, null=True)),
                ('payment_rejection_reason', models.TextField(blank=True, help_text='Reason for payment rejection', null=True)),
                ('payment_rejection_count', models.IntegerField(default=0, help_text='Number of times payment has been rejected')),
                ('last_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_notes', models.TextField(blank=True, help_text='Notes from coordinator about the payment', null=True)),
                ('client_notes', models.TextField(blank=True, help_text='Notes from client about the payment', null=True)),
                ('payment_instructions', models.TextField(blank=True, help_text='Payment instructions sent to the client', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_slip_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_bank_slips', to=settings.AUTH_USER_MODEL)),
                ('payment_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('payment_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payments', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Payment',
                'verbose_name_plural': 'Project Payments',
                'db_table': 'project_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
