# Generated by Django 5.0 on 2026-02-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_estimated_value_projectpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_completed',
            field=models.BooleanField(default=False, help_text='Whether the client has completed payment for this project'),
        ),
    ]
