# Generated by Django 5.0 on 2026-02-19 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_add_cancellation_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpayment',
            name='agent_paid_at',
            field=models.DateTimeField(blank=True, help_text='When the agent was paid', null=True),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='agent_paid_by',
            field=models.ForeignKey(blank=True, help_text='Coordinator who recorded the agent payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='agent_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid to the agent for this project', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='agent_payment_notes',
            field=models.TextField(blank=True, help_text='Notes about the agent payment', null=True),
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='agent_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', help_text='Status of the agent payment', max_length=20),
        ),
    ]
