# Generated by Django 5.0 on 2026-02-19 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectpayment_agent_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(help_text='Generated PDF commission report', upload_to='commission_reports/%Y/%m/')),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Commission amount in the report', max_digits=12)),
                ('sent_to_agent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_commission_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_commission_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_reports', to='projects.project')),
            ],
            options={
                'verbose_name': 'Commission Report',
                'verbose_name_plural': 'Commission Reports',
                'db_table': 'commission_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
