# Generated by Django 5.0 on 2025-11-25 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('land', 'Land'), ('building', 'Building'), ('vehicle', 'Vehicle'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square meters', max_digits=10, null=True)),
                ('land_type', models.CharField(blank=True, help_text='e.g., Residential, Commercial, Agricultural', max_length=100)),
                ('land_location', models.CharField(blank=True, max_length=500)),
                ('land_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('land_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('building_area', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square meters', max_digits=10, null=True)),
                ('building_type', models.CharField(blank=True, help_text='e.g., House, Apartment, Commercial Building', max_length=100)),
                ('building_location', models.CharField(blank=True, max_length=500)),
                ('building_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('building_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('number_of_floors', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('vehicle_registration_number', models.CharField(blank=True, max_length=50)),
                ('vehicle_mileage', models.IntegerField(blank=True, null=True)),
                ('vehicle_condition', models.CharField(blank=True, help_text='e.g., Excellent, Good, Fair, Poor', max_length=50)),
                ('other_type', models.CharField(blank=True, max_length=200)),
                ('other_specifications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('field_officer', models.ForeignKey(limit_choices_to={'role__role': 'field_officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='projects.project')),
            ],
            options={
                'verbose_name': 'Valuation',
                'verbose_name_plural': 'Valuations',
                'db_table': 'valuations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValuationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='valuation_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='valuations.valuation')),
            ],
            options={
                'verbose_name': 'Valuation Photo',
                'verbose_name_plural': 'Valuation Photos',
                'db_table': 'valuation_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
