# Generated by Django 5.0 on 2025-12-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is rejected'),
        ),
    ]
