# Generated by Django 5.0 on 2025-12-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0002_valuation_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='final_report',
            field=models.FileField(blank=True, help_text='Final valuation report uploaded by senior valuer for MD/GM approval', null=True, upload_to='final_valuation_reports/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='senior_valuer_comments',
            field=models.TextField(blank=True, help_text='Comments from senior valuer during review'),
        ),
    ]
