# Generated by Django 5.0 on 2025-12-21 12:29

from django.db import migrations, models


def set_default_senior_valuer_comments(apps, schema_editor):
    """Set default empty string for any NULL senior_valuer_comments"""
    Valuation = apps.get_model('valuations', 'Valuation')
    Valuation.objects.filter(senior_valuer_comments__isnull=True).update(senior_valuer_comments='')


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0003_valuation_final_report_and_more'),
    ]

    operations = [
        # First, update any NULL values to empty string
        migrations.RunPython(set_default_senior_valuer_comments, migrations.RunPython.noop),
        # Then alter the field to have default=''
        migrations.AlterField(
            model_name='valuation',
            name='senior_valuer_comments',
            field=models.TextField(blank=True, default='', help_text='Comments from senior valuer during review'),
        ),
    ]
