# Generated by Django 5.0 on 2026-02-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0004_alter_valuation_senior_valuer_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='submitted_report',
            field=models.FileField(blank=True, help_text='PDF report generated and uploaded by field officer on submission', null=True, upload_to='submitted_valuation_reports/%Y/%m/%d/'),
        ),
    ]
