# Generated by Django 5.0 on 2026-02-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0006_valuation_accessor_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='md_gm_comments',
            field=models.TextField(blank=True, default='', help_text='Comments from MD/GM during final approval'),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('md_approved', 'MD/GM Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
