# Generated by Django 5.0 on 2026-02-19 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_commissionreport'),
        ('valuations', '0007_add_md_approved_status_and_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('rejection', 'Rejection'), ('approval', 'Approval'), ('submission', 'Submission')], default='rejection', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('valuation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='valuations.valuation')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValuationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted by Field Officer'), ('resubmitted', 'Resubmitted by Field Officer'), ('reviewed', 'Accepted by Assessor'), ('rejected_by_accessor', 'Rejected by Assessor'), ('approved_by_sv', 'Approved by Senior Valuer'), ('rejected_by_sv', 'Rejected by Senior Valuer'), ('md_approved', 'Approved by MD/GM'), ('rejected_by_mdgm', 'Rejected by MD/GM')], max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='valuations.valuation')),
            ],
            options={
                'db_table': 'valuation_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
