# Generated by Django 5.0 on 2026-02-18 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_logs', '0003_alter_systemlog_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='User affected by the action', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='targeted_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
